Page({
  data:{
    imgs:[
      'http://img02.tooopen.com/images/20150928/tooopen_sy_143912755726.jpg',
      'http://img06.tooopen.com/images/20160818/tooopen_sy_175866434296.jpg',
      'http://img06.tooopen.com/images/20160818/tooopen_sy_175833047715.jpg'
    ]
  },
  choose(){
    wx.chooseImage({
      count:false,
      sizeType:'original',

    })
  },
  record(){
    const manager=wx.getRecorderManager()
    manager.start()
  },
  photo(){
    const photos=wx.createCameraContext(this)

    photos.takePhoto({
      success(res){
        console.log(res)
      }
    })
  },
  system(){
    wx.getSystemInfo({
      success(res){
        console.log(res)
      }
    })
  },
  brateL(){
    wx.vibrateShort()
  }
  ,
  nfc(){
    wx.getHCEState({
      success(res){
        console.log(res)
      }
    })
  },
  login(){
    wx.login({
      success(res){
        console.log(res)
      }
    })
  },
  auth(){
    wx.authorize({
      scope:'scope.record'
    })
  }
})